# Generated by Django 5.0.6 on 2026-06-09 06:57

from django.db import migrations

def seed_default_categories(apps, schema_editor):
    Category = apps.get_model('backend', 'Category')
    default_categories = [
        {"name": "Authentication", "slug": "authentication", "icon_name": "Key"},
        {"name": "Payment Issues", "slug": "payment-issues", "icon_name": "CreditCard"},
        {"name": "Email Problems", "slug": "email-problems", "icon_name": "Mail"},
        {"name": "Account Management", "slug": "account-management", "icon_name": "Shield"},
        {"name": "System Errors", "slug": "system-errors", "icon_name": "HardDrive"},
        {"name": "Order Tracking", "slug": "order-tracking", "icon_name": "Package"},
    ]
    for cat in default_categories:
        Category.objects.get_or_create(
            slug=cat["slug"],
            defaults={"name": cat["name"], "icon_name": cat["icon_name"]}
        )

def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('backend', 'Category')
    slugs = ["authentication", "payment-issues", "email-problems", "account-management", "system-errors", "order-tracking"]
    Category.objects.filter(slug__in=slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, reverse_code=remove_default_categories),
    ]
